### ISSUE TITLE
morning

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#1]
<img src="https://arasatasaygin.github.io/openlogos/logos/morning.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/morning-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by michaelmior** [comment]
Inspired by Good Mythical Morning? :)

**Comment by NghiaTranUIT** [comment]
Hello folks, I'd to claim this logo since the cock in the morning is a perfect candidate for my Artify, which is a macOS app to bring 18th art to everyone every morning 😍.

I fall in love immediately when I see this logo. The cock and the beautiful color of the background represent what Artify does.

Check it out https://github.com/NghiaTranUIT/artify-macos 🌎

**Comment by arasatasaygin** [comment]
@michaelmior epic series. Never realized but honestly it can be the influence :)
@NghiaTranUIT Artify look classy. Good luck.

**Comment by NghiaTranUIT** [comment]
Thank you @arasatasaygin your contribution.
Hope I will get it 👍

**Comment by Zimmi48** [comment]
Hi, I'd like to claim this logo for coq-community (https://github.com/coq-community). [Coq](https://coq.inria.fr) is a proof assistant and programming language with dependent types and coq-community is a project for the collaborative long-term maintenance of Coq packages and their advertisement (for more details, see https://github.com/coq-community/manifesto). Thanks!

**Comment by christhekeele** [comment]
Awesome to see venerable projects like coq on here!

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/morning-guide.jpg?v=2">

Congrats @Zimmi48 🐓

Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
