### ISSUE TITLE
birdangle

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#11]
<img src="https://arasatasaygin.github.io/openlogos/logos/birdangle.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/birdangle-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by arasatasaygin** [comment]
Hello @hattan 
Thanks for claiming. Kairo looks great. Cheers.

**Comment by christhekeele** [comment]
Hey @hattan!

While the colors here are Slack-esque, have you thought about the [flame](https://github.com/arasatasaygin/openlogos/issues/9) logo? It seems a good fit with the name Kairo (re: capital of Egypt, home of the pyramids, Cairo).

**Comment by hattan** [comment]
Hey @christhekeele - thanks for the feedback, I do agree flame looks good. Just personally I think birdangle fits in better. But that's a subjective opinion :)

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/birdangle-guide.jpg">

Congrats @hattan          
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone.
Cheers

~ Aras
