### ISSUE TITLE
moby

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#12]
<img src="https://arasatasaygin.github.io/openlogos/logos/moby.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/moby-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by Jasius** [comment]
I'd love this for theme that I made for reddit platftorm https://github.com/Jasius/Windows-theme  https://clearshift.jaska.co/

**Comment by crnbrdrck** [comment]
Hi there! Might I just start off by saying that this is an amazing project!

I recently started work on a browser extension called [github-user-languages](https://github.com/crnbrdrck/github-user-languages)!

It's a simple little tool that when installed displays a nice little pie chart of all a user's languages that they have for their repos on GitHub, and you can click the individual languages to be shown a list for that language by the user.

I would love to put this project down for this logo, mainly because I really love the design!

Thank you for your time! :heart:

**Comment by arasatasaygin** [comment]
Hello everyone and thanks for kind words.
@Jasius thanks for building this. Reddit is an incredible community.
@crnbrdrck loved your project. Cheers.

**Comment by crnbrdrck** [comment]
Hey @arasatasaygin, I'm just going to let you know here that a user has actually opened an issue on my project asking to contribute a logo he designed specifically for it so in the interest of fairness I would like to withdraw my claim for this logo and leave it available for another deserving project to receive it instead.

Thank you again for this amazing initiative, and if you ever need help with anything please do not hesitate to drop me an email :smile:

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/moby-guide.jpg">

Congrats @crnbrdrck 
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras

**Comment by Jasius** [comment]
Welp

**Comment by arasatasaygin** [comment]
:) sorry just saw the comment @Jasius

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/moby-guide-2.jpg?v=2">

I updated the style guide for your project @Jasius 
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for baring with me 😂 
Cheers

~ Aras

**Comment by betsythefc** [comment]
Can this logo be claimed by more than one project?

**Comment by garrettw** [comment]
No, and it's not. The winner withdrew.

**Comment by Jasius** [comment]
Sorry bud.
