### ISSUE TITLE
blush

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#13]
<img src="https://arasatasaygin.github.io/openlogos/logos/blush.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/blush-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by dreamingechoes** [comment]
Hi @arasatasaygin!

First of all, thank you for this initiative, it's awesome! 😄 

I'd like to request this logo for a project I'm working on and I plan to finish and publish to production this summer: [Diversity In Tech](https://github.com/dreamingechoes/diversity-in-tech). It's an application made with Phoenix Framework to rate tech companies according to how diverse friendly they are. 

It will be online so the people can take rate and also search for the most diverse tech companies, and it will be open source so anyone can make its contribution to the project.

Thank you! 😄

**Comment by arasatasaygin** [comment]
Thanks for kind words and building this @dreamingechoes Cheers.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/blush-guide.jpg">

Congrats @dreamingechoes 
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Cheers

~ Aras
