### ISSUE TITLE
neo

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#14]
<img src="https://arasatasaygin.github.io/openlogos/logos/neo.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/neo-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by ThemesGuide** [comment]
I would like to claim the "Neo" logo project for my free themes project: https://github.com/themesguide/bootstrap-themes

I think the colorful, geometric design of "Neo" would be a perfect fit for the diverse, bold color palette of our themes. Thank you!

**Comment by kitze** [comment]
This looks like a nice icon for JSUI!

https://github.com/kitze/JSUI

It's a powerful UI toolkit for managing JavaScript apps.

**Comment by manekinekko** [comment]
Hi @arasatasaygin I really like your work. I've been looking for a nice logo creation for my app https://xlayers.app. Any chance I can claim this logo? 🙏

![image](https://user-images.githubusercontent.com/1699357/41596522-e0bcd406-73ca-11e8-9733-69fc9d244e0a.png)

**Comment by deedubs** [comment]
I'm building a secure by default Kubernetes distribution called MassiveKube. Its a high security, resilient, batteries included Kubernetes deployment. This logo would work perfectly.

https://github.com/massiveco/massivekube

Thanks for your consideration 😄

**Comment by sal2993** [comment]
Me and a friend are building an archives of top HackerNews posts incase you need to see an old top post and its score/duration-as-top-post.
Would love to have this logo! site: https://hackernews.tech
![screenshot 2018-06-19 08 42 52](https://user-images.githubusercontent.com/9065641/41604577-d2970b0e-739c-11e8-9f2e-85c508bf299d.png)

**Comment by karpatic** [comment]
Hi! 

Org : Baltimore Neighborhood Indicators Association (Bnia.org)
Project  : Bnia Builder
GitHub : https://github.com/bnia/bniaBuilder
Live Example(s) : Bniajfi.org/bold & Bniajfi.org/greenpatterns/beta
Premise : Allow civic leaders to develop highly dynamic, accessible, real-time distributed GIS data exploration, analysis, recommendations (ML), and visualization PWA's with a simple configuration/ setup that should not require a programmer.

Why we would like this Logo : As I understand it, this Cube represents (insert-city-here). The Logo's Gestalt groupings/ colors represent the disparate data-sets coming together to form this image of Baltimore.

Thank you for this opportunity. I really do have so much respect for what you are doing!

**Comment by raulk** [comment]
I dig the vibrant colours and the line shapes! 😍 

I'd love to associate this logo with ethql – a GraphQL interface to Ethereum! (under heavy development)

Check it out here: https://github.com/ConsenSys/ethql

**Comment by OKNoah** [comment]
My project is currently called [Final](https://gitlab.com/NoahGray/final); it's maybe best described as "React for the web server". If supports HTTP and WebSockets but handles it all with a "Component" with React-like lifecycle events. All data modelling is done similar to using "PropTypes" but with Flow instead. So it's kind of a Modal/Controller in one, where you can add functionality via decorators. Currently it supports an [ArangoDB](https://www.arangodb.com) plugin/decorator and a [Redux](https://redux.js.org) add-on. In the project I show examples of using it as game server and other things.

**Comment by mirimmad** [comment]
Hello there, I am a high schooler. I have been implementing a programming language since last 6-7 months. This logo would be perfect for my PL.

**Comment by OKNoah** [comment]
@mirimmad Awesome to hear someone like yourself is making a programming language! But this is for open source projects, and unless your project has source code that includes and open source license, it doesn't qualify-- but simply upload your code and include an open source license and you're eligible! Plus how an I vote for you if I can't see the project? Looking forward to it, and good luck.

**Comment by mirimmad** [comment]
@OKNoah Noah! The project will be open sourced within 1.5 months. 
It's Okay if you give away the logo to someone else for now. I can ping you later on Twitter when the project is open sourced so that you can have a look. 
Maybe you could provide me the same logo then with some minor edits.

**Comment by imolorhe** [comment]
Hey! This would be a nice logo for altair! https://github.com/imolorhe/altair

It is a graphQL client/IDE. Slowly gaining traction too. This would be a nice start of a makeover. 😊
![Altair GraphQL Client](https://github.com/imolorhe/altair/raw/staging/src/assets/img/readme/app-shot.jpg)

**Comment by DandyDev** [comment]
@manekinekko it says in the readme of openlogos that these logos are meant for open source projects, but I can't seem to find the repo for xLayers anywhere. Am I missing something here?

**Comment by sirkadirov** [comment]
Hi! My name is Yurij Kadirov and I'm developing programming contests management system with additional functionality called "SimplePM".

SimplePM is useful for schools and unoversities, where students learn programming. Also, you can use system on programming contests like ACM ICPC and IOI.

At this moment, project is being used by 2 schools in Ukraine, what is good for 2-year project.

Website: https://spm.sirkadirov.com/

https://github.com/SirkadirovTeam/SimplePM_Server

https://github.com/SirkadirovTeam/SimplePM_WebApp

Thank you for your OpenLogos project!

**Comment by kureikain** [comment]
Hi,

My name is Vinh. I build this https://noty.im

The project is 100% open source so one can self-hosted themselves:

- https://github.com/notyim/trinity
- https://github.com/notyim/gaia

It's an uptime monitoring tools but I want to add more feature on different kind of monitoring given I have the notification layer and the scanner build out.

Thank you.

**Comment by occupant23** [comment]
rechecked, works for one argument, but doesn't for more. please fix

**Comment by alex-ppg** [comment]
Hello everyone,

We are creating a fully open-source decentralised wallet for cryptocurrencies that will also host a peer-to-peer exchange in the future.

We believe the logo is ideal for the project due to its similarity with a block.

You can find the live version of the wallet (Without any form of tracking, not even a Google tag) on https://wallet.arctus.io/.

Alternatively, feel free to visit our repository at https://github.com/arctuswallet/Arctus-Wallet.

Good luck to all!

**Comment by onokumus** [comment]
Merhaba @arasatasaygin 

Bu logo https://github.com/onokumus/metismenu projesine çok yakışır diye düşünüyorum.

Başarılar.

**Comment by mirimmad** [comment]
@OkNoah the project is open source now.

**Comment by OKNoah** [comment]
@mirimmad Cool! I am not much of an expert, but looks neat.

**Comment by LaurenceUrhegyi** [comment]
Hello!

As has been stated before, this is such a great idea, a really good way for small FOSS projects to get a sweet logo!  

I'd like to put forward [BuildGrid](https://gitlab.com/BuildGrid/buildgrid) for this logo. BuildGrid is a remote execution server, written in Python, that implements Google's Remote Execution and Remote Workers APIs. It's designed to work with build tool clients such as [BuildStream](https://gitlab.com/BuildStream/buildstream) and [Bazel](https://bazel.build).

I really think this would suit the style of the project, since it seems to represent a 'grid' of inter-connected events - the very nature of distributed builds ! 

Thanks for putting the time in to create such nice logos :)

Best,
Laurence

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/neo-guide.jpg">

Congrats @deedubs           
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone. Fun fact: I was considering to not include this one to the batch, but it got great reactions from you people, so thanks :)
Cheers

~ Aras
