### ISSUE TITLE
sage

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#15]
<img src="https://arasatasaygin.github.io/openlogos/logos/sage.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/sage-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by 73rhodes** [comment]
I'm sure there are more worthy project but I'll propose `[dclassify](https://github.com/73rhodes/dclassify)` - a simple bayesian binary classifier for node.

**Comment by Pierre-Sassoulas** [comment]
Hi,

Great idea and very nice logos :)

I'd like to claim this logo for [django-survey-and-report](https://github.com/Pierre-Sassoulas/django-survey). This is an app to create survey with the django framework. A little like "lime survey" but for developpers that already have a python/django project/server up and running and do not want to go full LAMP just for a survey.

I like the fact that the owl in the logo seems to be watching and listening. It could symbolise the surveying and the listening to what the user says. After listening the app is "sage" and can do the reporting.

Regards,
Pierre Sassoulas

**Comment by arasatasaygin** [comment]
Hey, thank for kind words.
Both dclassify and django-survey-and-report projects look great. Thanks for claiming. Cheers.

**Comment by hobbypunk90** [comment]
Hey,

your logos are great 😊 and i really love this idea 🙂

A friend and me started our project [Guardian of Times](https://github.com/LiScI-Lab/Guardian-of-Times) as a replacement for time tracking with sheets at our university. It is a little Ruby on Rails application where users can create or join teams to group, track and tag their working times.

The reason why we would like to claim "sage" is similar to @Pierre-Sassoulas - the owl watches over our times 😁

Regards,
Marcel

**Comment by Nelson-numerical-software** [comment]
Hi, 
This logo could be great to represent Nelson
https://nelson-numerical-software.github.io/nelson-website/

Nelson is an array programming language providing a powerful open computing environment for engineering and scientific applications using modern C/C++ libraries (Boost, Eigen, …) and others state of art numerical libraries.

It has sophisticated data structures (including cell, struct, linear systems, …), an interpreter and a high level programming language.

Nelson has been developped to be an open/modular system where an user can define these own data types and operations on these data types by using overload.

Thanks

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/sage-guide.jpg">

Congrats @hobbypunk90 
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
