### ISSUE TITLE
charlie

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#16]
<img src="https://arasatasaygin.github.io/openlogos/logos/charlie.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/charlie-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by Tophat** [comment]
This looks like a perfect logo for Tophat!

I've built a collection of open-source (MIT) themes to stylize your Bootstrap projects:

https://github.com/Tophat/themes

**Comment by ldidry** [comment]
I have an URL shortening software called [Lstu](https://lstu.fr) (Let's Shorten That Url) that have a bowler hat as logo but this one would be a major improvment!

My project's repo: https://framagit.org/luc/lstu/

My current logo:
![Logo of Lstu](https://lstu.fr/img/lstu.png)

**Comment by arasatasaygin** [comment]
Hello, thanks for claiming.
Both of your project look like a great fit. Cheers @Tophat @ldidry

**Comment by WorldMaker** [comment]
That's not a top hat, that's a bowler or derby.

**Comment by Tophat** [comment]
@WorldMaker - true, which is why we may alter it if we get the claim for Charlie.

**Comment by bbabkin** [comment]
![tophat](https://user-images.githubusercontent.com/9200607/42671704-660db6ae-862f-11e8-9b20-d0dceb76372e.jpg)
if u like - enjoy
if u rich and generous - send $
if u hot gurl - send nudes
:)

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/charlie-guide.jpg">

Congrats @ldidry   
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras

**Comment by ldidry** [comment]
Awesome! Thank you very much! :tada:
