### ISSUE TITLE
steps

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#17]
<img src="https://arasatasaygin.github.io/openlogos/logos/steps.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/steps-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by mtharrison** [comment]
Hey I'm building a browser-based interactive Wasm (webassembly) disassembler. Its goal is to teach people about the webassembly format, webassembly code and how the stack machine works. The cool thing is it will also be written in Rust and compiled to wasm. Wasm all the way down!

The app will allow a user to upload a compiled wasm file and then inspect all the sections in the binary including functions, data and of course the disassembled code. I'm also planning to build a stack machine simulator so you can see how the code gets executed for real.

I'm just getting started really so I can't show anything very cool yet but the project is living here:

https://github.com/mtharrison/wasmparse-core - Core wasm parser written in Rust
https://github.com/mtharrison/wasmparse-bridge - Bridge for the core parser to be used in browser (compiled to wasm of course!)
https://github.com/mtharrison/wasmparse-web - The web frontend - this is where the interactivity will work.

**Comment by leonsegal** [comment]
I am making a pragmatic solution to the packing problem: https://github.com/leonsegal/packman

Please let me have this logo so I won't get sued for copyright. I will probably need to change the name too.

**Comment by harababurel** [comment]
I would like to claim this logo for GCSF, the subject of my bachelor's thesis.

GCSF is a virtual file system built on top of Google Drive. It is implemented in Rust and aims to provide efficiency and stability. I think this logo is a good match for the project.

You can try it out by following the instructions found on [github.com/harababurel/gcsf](https://github.com/harababurel/gcsf). Keep in mind that it is still a work in progress, but most features should work out of the box. [Here](https://sergiu.ml/~sergiu/thesis.pdf) is a rough draft of the paper that I am writing on it.

Thank you for the initiative!

**Comment by Vtrois** [comment]
First of all, thanks to the author, this is a great project :+1: 

I'm worried about designing logo for my project, this project is really too timely. My project name is SpacePack ( github.com/Vtrois/SpacePack ), It is the necessary toolbox for the Operations Engineer.

It's a pity that the project is being made, but it will be released.

Thank you for your project!

**Comment by garrettw** [comment]
This is already the logo of [Kalabox](https://www.kalabox.io/).

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/steps-guide.jpg">

Congrats @mtharrison           
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone.
Cheers

~ Aras

**Comment by Polqt** [comment]
Hey there, I'm building an inventory web-app name "Stocktory" for my Cloud Based project in this term. The goal of this web-app Stocktory is a cloud-based inventory management web app designed to help users efficiently track and manage their inventory. The web app aims to streamline the process of inventory tracking by providing an intuitive interface where users can read, add, update, delete, and monitor their stock levels. With features like inventory categorization, low-stock alerts, and detailed reporting, Stocktory empowers users to maintain optimal stock levels and reduce the risk of stockouts or overstocking. The project is currently under development and is available on https://github.com/Polqt/inventory, where you can follow its progress and contribute to its growth.
