### ISSUE TITLE
aysha

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#19]
<img src="https://arasatasaygin.github.io/openlogos/logos/aysha.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/aysha-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by aconrad** [comment]
Hi! I'd like to use this logo for [pycobertura](https://github.com/aconrad/pycobertura), a code coverage diff tool for Cobertura reports.

**Comment by JohnnyQPubic** [comment]
I would like to use this logo for my Child Rape Awareness t-shirt I am working on.

**Comment by ElPresidentePoole** [comment]
THAT'S A BAD ONE JOHNNY

**Comment by arasatasaygin** [comment]
Hey, thanks for claiming this logo @aconrad 
pycobertura looks great. Cheers.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/aysha-guide.jpg">

Congrats @aconrad            
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting.
Cheers

~ Aras
