### ISSUE TITLE
recurse

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#20]
<img src="https://arasatasaygin.github.io/openlogos/logos/recurse.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/recurse-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by Cretezy** [comment]
I'd like to claim this logo for my project [Noderize] (https://github.com/Cretezy/Noderize) since the logo is already a hexagon :)

Thank you very much! This is a great initiative!

**Comment by OKNoah** [comment]
My project is currently called [Final](https://gitlab.com/NoahGray/final); it's maybe best described as "React for the web server". If supports HTTP and WebSockets but handles it all with a "Component" with React-like lifecycle events. All data modelling is done similar to using "PropTypes" but with Flow instead. So it's kind of a Modal/Controller in one, where you can add functionality via decorators. Currently it supports an [ArangoDB](https://www.arangodb.com) plugin/decorator and a [Redux](https://redux.js.org) add-on. In the project I show examples of using it as game server and other things.

**Comment by sirkadirov** [comment]
Hi! My name is Yurij Kadirov and I'm developing programming contests management system with additional functionality called "SimplePM".

SimplePM is useful for schools and universities, where students learn programming. Also, you can use system on programming contests like ACM ICPC and IOI.

At this moment, project is being used by 2 schools in Ukraine, what is good for 2-year project.

Website: https://spm.sirkadirov.com/

https://github.com/SirkadirovTeam/SimplePM_Server

https://github.com/SirkadirovTeam/SimplePM_WebApp

Thank you for your OpenLogos project!

**Comment by learnbyexample** [comment]
@arasatasaygin, Nice initiative! thanks for doing this

I'd like to claim this logo for my example based [Command Line Text Processing](https://github.com/learnbyexample/Command-line-text-processing) book

The project introduces various cli tools like grep, sed, awk, perl, ruby, sort, pr, paste, etc with plenty of examples. I've been working on it for more than a year and has over 7k stars. Seeing this project [shared in various forums](https://gist.github.com/learnbyexample/2158966896c65beb6963a3b019320902#featured) has been very satisfying and helped me to continue adding more chapters.

**Comment by arasatasaygin** [comment]
Hello everyone,

@amitmerchant1990 I like what you are doing with markdownify.
@Cretezy great documentation on Noderize. I'll try to build some small projects with it.
@OKNoah thanks for claiming. Final looks good.
@sirkadirov hope you the best with simplePM Yuri
@learnbyexample thanks for making this open source sir.

Thanks for the kind words.
Cheers

**Comment by fxfactorial** [comment]
Hello, 

I run https://yerevancoder.com/ which is the only community public open source tech project in Armenia, https://github.com/yerevancoder/yerevancoder.github.io

We need some kind of logo and this logo in particular is similar enough to an Ancient Armenian symbol of eternity as well, հավերժության նշան,

https://en.wikipedia.org/wiki/Armenian_eternity_sign

![](https://en.wikipedia.org/wiki/Armenian_eternity_sign#/media/File:Right-Facing_and_Left_Facing_Armenian_Eternity_Sign.svg)

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/recurse-guide.jpg">

Congrats @Cretezy 
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras

**Comment by garrettw** [comment]
Typo in the logo 😉

**Comment by arasatasaygin** [comment]
:D Thanks for letting me know @garrettw 
Sending you the updated resources @Cretezy

**Comment by dreamZhf** [comment]
你好:
    申请使用此标志，用来做来安全识别二维码的LOGO

**Comment by Cretezy** [comment]
Just an update:

The logo is live at https://noderize.js.org

It looks great, thank you!

**Comment by arasatasaygin** [comment]
🔥🔥
