### ISSUE TITLE
viki

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#21]
<img src="https://arasatasaygin.github.io/openlogos/logos/viki.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/viki-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by miere** [comment]
Amazing logo! For an undisclosed reason it transmits me the feeling of someone who is in charge to make something great. Once the world is looking for **serverless** as an approach to scale their applications, thus I think it would be nice fit for [Lambdify](https://github.com/lambdify/lambdify) which intent to make JVM Lambda functions lighter and faster.

Lambdify is on its early stages, we just open sourced it, but it helped us a lot and I think it would benefit other teams too.

**Comment by kilroyc6** [comment]
This mine strong I have no fear like a viking

**Comment by philss** [comment]
This logo looks awesome, and is very aligned with the idea behind the name of [Floki](https://github.com/philss/floki), which is a HTML parser written in [Elixir](https://elixir-lang.org/), on top of mochiweb & html5ever.

The name Floki is inspired by the history of the viking [Hrafna-Flóki Vilgerðarson](https://en.wikipedia.org/wiki/Hrafna-Fl%C3%B3ki_Vilger%C3%B0arson), which sailed to Iceland in the 9th century. In fiction, we have the [Vikings TV series](https://www.imdb.com/title/tt2306299/) which shows [Gustaf Skarsgård playing Floki](http://vikings.wikia.com/wiki/Floki). I learned about Floki after watching the show.

Would be great to have this logo for Floki! 😄

**Comment by arasatasaygin** [comment]
Hello everyone, thanks for kind words and support.

@miere I would love to see you progress on this project. Great potential.
@kilroyc6   ^<(◣_◢)>^
@philss Floki.find(html, "p.thanksForClaimingThisLogo")

Cheers

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/viki-guide.jpg">

Congrats @philss 
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras

**Comment by philss** [comment]
@arasatasaygin Thank you very much! 💜 
The logo looks awesome with the project name! It is now on [Floki's README](https://github.com/philss/floki/blob/master/README.md). 🎉 😃
