### ISSUE TITLE
im-possible

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#22]
<img src="https://arasatasaygin.github.io/openlogos/logos/im-possible.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/im-possible-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by xemasiv** [comment]
Hi, Mr. Aras!

Love your work.

I would like to propose a claim for this beautiful logo for "fugitive",
a project I'm currently working on which aims to leverage the rise of
WebRTC in optimizing the way we resolve web assets in a secure,
efficient, pre-orchestrated manner.

My goal is to create an open-sourced approach in improving user experience
by further reducing latency, which will efficiently work well not only in urban areas
but also in last-mile-delivery cases (ie. end-users which are far from CDN / Cloud Delivery
Network endpoints), whether the content are images, videos or just plain binary files.

https://github.com/xemasiv/fugitive

The "F" in this wonderful art fits well for 'fugitive' and I can already
see myself walking down the street wearing a black / white shirt
with this amazing logo on it.

Best,
Joshua Samonte

**Comment by agis** [comment]
Hello Aras!

Thanks for this great initiative.

We ([@skroutz](https://github.com/skroutz)) would love to use this logo for [*mistry*](https://github.com/skroutz/mistry), a build server that enables fast workflows by pre-computing results of commands and caching them for later use. It also comes with a web UI, in which the logo could be a great fit.

We built _mistry_ to increase the speed of our deployments (we're on a Rails stack) and other pipelines (eg. installing dependencies). We successfully used it in the past three months and it greatly saved much developer time. We plan to continuously improve it by adding much needed features and make it a more robust solution.

**Comment by billniakas** [comment]
I would like to claim this logo for our Arch Linux installer which is called Archon (Archon is a greek word which means "Ruler") https://github.com/CerebruxCode/Archon and it is in active development.

The Logo looks like Α and we could use it for our project (in a way we ease the struggle of getting out of the maze that is the Arch Linux Installation)

Cheers
Bill Niakas

**Comment by pie6k** [comment]
Hello!

I'd like to claim this logo for [**typegql**](https://github.com/prismake/typegql) - project allowing you to **create GraphQL schema with TypeScript classes.**. Goal of this project is to take advantage of typed js language to auto-create graphql schema which is also strongly typed solution. It allows having only single source of truth for both schema shape and resolved values. 

To have working schema able to resolve query like: 
```graphql
query {
  hello(name: "Bob") # will resolve to 'Hello, Bob!'
}
```

You'd need only:
```ts
import { compileSchema, SchemaRoot, Query } from 'typegql';

@SchemaRoot()
class SuperSchema {
  @Query()
  hello(name: string): string {
    return `Hello, ${name}!`;
  }
}

const compiledSchema = compileSchema({ roots: [SuperSchema] });
```

Project is entirely covered with tests and I believe it could be really useful for rapid development of reliable Graphql api's.

Cheers,
Adam.

**Comment by Anymake** [comment]
i love this logo

**Comment by arasatasaygin** [comment]
Thanks for your kind words and claiming this logo everyone.

**Comment by gappleto97** [comment]
Hi!

I would like to claim this logo for the p2p.today project. It aims to create an easy, language-independent API for people to use for peer-to-peer networking, as an essentially drop-in replacement for things like socket.io.  It currently has an beta version available in Python and Javascript, with parsing support in C, C++, Java, and Golang (those last two being somewhat incomplete). That version works with TCP, websockets, and self-signed TLS. I am working on rewriting the protocol at the moment to allow other developers to more easily participate, and more formally support a variety of transport methods. For more info, see [py2p](https://pypi.org/project/py2p/) and [js2p](https://www.npmjs.com/package/js2p). The only thing not working in those examples is the bootstrap function, because I had to stop hosting my servers while I moved.

I like this logo in particular because it illustrates connectivity fairly well, while also having a somewhat retro feel to it.

Thanks,
Gabe

**Comment by ThatCynicalX** [comment]
I would like to claim this logo for [netclix](github.com/ston3o/netclix). It aims to use the VodLocker API to easily and effectively search for movies.

This, in my opinion, is a very nice logo because it has a very nice depth effect to it, and displays togetherness and inter-connectivity.
