### ISSUE TITLE
globe

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#24]
<img src="https://arasatasaygin.github.io/openlogos/logos/globe.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/globe-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by scalatapes** [comment]
Though not technically an open source project, I'd like to present my non-profit organisation in the hopes of claiming this logo.

I run a small, non-profit organisation called Scala. We promote diversity and accessibility (for individuals with a disability) within the local and european music scene. Several festivals and labels have white, male, cis-centric lineups and many events are not accessibility by wheel chair, or for guests with visual impairment. We work hard to change these facts and to promote our message.

We have several subdivisions, such as a music label, a music and arts festival called Lost Lands, and an upcoming podcasting platform.

To be clear, we are primarily producers of different audio- and arts-related cultural products, be it music, events, our festival or our podcasts / radio plays.

All of our projects are made possible with different grants, and all profits funnelled into other cultural activities.

http://www.scalatapes.net/
https://www.lostlandsfestival.net/

**Comment by devxpy** [comment]
Here is my project, ZProc. 

https://github.com/pycampers/zproc

Why I think this would be appropriate - 
It helps you do multiprocessing, using a global state. Hence the "globe".
The globe being fragmented, represents the multiple processes.

**Comment by pkkid** [comment]
You are both in different business domains, I vote you both get it. :D

**Comment by devxpy** [comment]
@pkkid wow! https://github.com/pkkid/pygrid

**Comment by austinbillings** [comment]
Not to detract from anyone claiming this logo, and not to discredit the artist, but I figure it's important to note that this is quite similar to the [AT&T Logo](http://www.brandemia.org/sites/default/files/sites/default/files/att_logo_evolucion_historia.jpg) 🤔

**Comment by rspeed** [comment]
Seconding @austinbillings. I'm not a lawyer, but it's similar enough that I'd be worried about a trademark suit.

**Comment by jcelerier** [comment]
funny, my first though was the old [Sierra logo](https://www.google.fr/search?q=sierra+logo&tbm=isch)

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/globe-guide.jpg">

Congrats @devxpy   
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher. If you have any concerns about AT&T and Sierra feel free to not use it :)

@scalatapes thanks for claiming but for this batch, I'm distributing to open source projects.

Thanks again everyone for the support.
Cheers

~ Aras

**Comment by devxpy** [comment]
@arasatasaygin Thank you!

Also, I would use it just for having a chance to say this - "AT&T contacted me" xD
