### ISSUE TITLE
bug-lock

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#25]
<img src="https://arasatasaygin.github.io/openlogos/logos/bug-lock.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/bug-lock-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by mvasilkov** [comment]
Hi! This is such a beautiful thing, I love it :)

I'd like to claim the bug-lock for my pet project, https://github.com/mvasilkov/longpaste

Longpaste is an open source Node.js pastebin site with focus on users' privacy. As such it does not rely on third-party login or captcha providers such as Google; we use clever tactics like in-browser PoW to prevent automated posting.

Longpaste can be run separately, or used as a REST API backend. There is at least one project that's based on Longpaste already, see https://project-txt.com (it's in development, with only the basic functionality available at moment).

I feel like the creeping HTTPS lock is a great metaphor for a privacy-related project.

Thanks!

**Comment by work-dharmendra** [comment]
This project is very good and unique.
I'd like to claim the bug lock for my http://almond-automation.blogspot.com/p/home.html.

Almond Automation is codeless web automation testing tool based on selenium grid.
User can create, run and view testcase without writing any code.
User can easily create and maintain testcases and testsuites and run multiples testcases from single UI.

**Comment by SpaceK33z** [comment]
Hi, this logo is awesome!

I'd like to claim the bug-lock for my project, https://github.com/Volst/prisma-auth/

Prisma Auth makes dealing with authentication easy for Prisma, which is sort of an ORM specifically designed for use in GraphQL. It will soon be refactored to be more generic (it's Prisma-specific now, but will be only GraphQL specific soon) so it will attract a broader audience. I think the logo fits perfectly as a play on GraphQL's logo and the lock which could stand for the authentication part.

**Comment by arasatasaygin** [comment]
Hello everone.
@mvasilkov Headline of your project is catchy :) The opposite of a shortcut.
@work-dharmendra Can you please share repo, I couldn't find it. Thanks for supporting.
@SpaceK33z GraphQL is my next shiny thing syndrome for sure. Thanks for claiming this logo and good work on prisma-auth

**Comment by codeSamuraii** [comment]
Hello, this is really nice work. 👍 

I'm candidating for this logo with my project [CryptoTCP](https://github.com/codeSamuraii/CryptoTCP).
It is a Python module that allows you to easily implement a secure communication tunnel with hybrid (RSA + AES) encryption. It is still in early stages of development, but a new version will come out soon.
The lock refers nicely to both the name and the purpose of my project. 🕷

**Comment by rpellerin** [comment]
Great logo! Perfectly suited to my project, [Gauth2](https://github.com/rpellerin/gauth2/).

Initially a forked project, it has been completely rewritten in React and Redux, with added features. **It's a web app that allows users to generate one time passwords (OTP)**, just like Google Authenticator does. Users can either paste images containing a QR code, or fill in the secret string, when enabling two factor authentication, and then generate OTP any time they need. The app stores the secrets in the localStorage, not on a server.

What's this project good for? Well, it comes in very handy when one wants to log in to Facebook, Google, Twitter, ... essentially any website that offer two factor authentication. No need to open up an app on your smartphone or wait for a text containing the code, just visit a website that hosts the project, or the [demo page](https://github.com/rpellerin/gauth2/), and you'll get your OTP.

**Comment by Dharmendra-Chouhan-mpf** [comment]
@arasatasaygin : my github repo is at https://github.com/work-dharmendra/almond-automation.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/bug-lock-guide.jpg">

Congrats @SpaceK33z    
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
