### ISSUE TITLE
rayray

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#27]
<img src="https://arasatasaygin.github.io/openlogos/logos/rayray.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/rayray-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by avenirer** [comment]
Hello, I would like to present you an app that aims to track tasks. The app is made using CodeIgniter 3. The name I chose came as result of a word play (task, tusk). I was thinking that a boar or a rhinoceros would be representative as a logo.  https://github.com/avenirer/Tusker
Thank you.

**Comment by arasatasaygin** [comment]
Hello everyone, thanks for supporting and all kind words.

@avenirer nice work on Tusker.
@BTaskaya wow! (Gurur duydum)

Cheers.

**Comment by adamculpepper** [comment]
@avenirer Rhinoceros don't have tusk, they have horns. ;)

**Comment by cemremengu** [comment]
@BTaskaya looks like we have genius here, keep it up! 🙏

**Comment by BTaskaya** [comment]
@cemremengu thx.

**Comment by Spomky** [comment]
Hi,

For [my project](https://github.com/web-token), this logo will be awesome compared to the actual one.

This project is a complete framework for Json Web Token (JWT) management for PHP.
It covers all approved IETF specifications and supports dozen of signature and encryption algorithms, compression methods and all serialization methods. And if it is not enough, you can easily extend its capabilities with your own/custom implementations.

From my POV, a rhinoceros like this one perfectly fits to that project as it represents stability and security.

![traffic web token jwt framework](https://user-images.githubusercontent.com/1091072/41958024-16678c76-79e9-11e8-82d9-dcf524342f18.png)

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/rayray-guide.jpg">

Congrats @BTaskaya  🦏
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
