### ISSUE TITLE
inspector

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#28]
<img src="https://arasatasaygin.github.io/openlogos/logos/inspector.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/inspector-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by joereynolds** [comment]
The seems like a pretty apt fit for [Mort](https://github.com/joereynolds/mort), my tool for detecting dead css ! It *inspects* (nudge nudge wink wink, inspector) your CSS and reports back with any possible dead selectors.

**Comment by wkoszek** [comment]
First of all: excellent idea to promote your design. Your logos look great.

2 days and no takers for this logo? Come on GitHub people!

It's clear: this shady guy would be perfect for my https://github.com/wkoszek/lastpass-ssh 
What better logo can there be for a tool which you give an access to your LastPass and SSH keys than a shady guy?

It's a little tool, but people seem to like it. I'd only want to claim this logo is nobody else comes up with a better idea.

**Comment by johnrengelman** [comment]
This is a great idea!

I’d like to nominate the Gradle Shadow plugin: https://github.com/johnrengelman/shadow 
Shadow is a Gradle plugin that creates a single “fat” JAR of an application and is one of the more widely downloaded plugins (over 3 million downloads in the last year)

It was originally a port of Maven’s Shade plugin: https://maven.apache.org/plugins/maven-shade-plugin/

Shadow already plays on its name by referencing the legendary comic book character: https://en.m.wikipedia.org/wiki/The_Shadow

Thanks for the consideration and remember:
THE SHADOW KNOWS!

**Comment by arasatasaygin** [comment]
Hello and thanks for all kind words. 
Loved both lastpass-ssh and shadow. Thanks for claiming this logo for your projects @wkoszek @johnrengelman 

Cheers.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/inspector-guide.jpg">

Congrats @johnrengelman 🥇 

Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
