### ISSUE TITLE
cosmos

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#29]
<img src="https://arasatasaygin.github.io/openlogos/logos/cosmos.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/cosmos-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by zvr** [comment]
I am interested in this for a new open source project currently being developed under the Google Summer of Code program.
However, some minor modification are going to be needed.

@arasatasaygin would you consider providing a variation (e.g., different colors to match our palette) ?

**Comment by esl-douglas** [comment]
I'm interested in this logo for my open source church presentation software, currently named bartimeu.

[Github repository currently in development](https://github.com/dodopok/bartimeu/tree/electron)

**Comment by nukeop** [comment]
I would like to use this logo for an open source sci-fi themed game I'm developing.

It can be found here: https://github.com/nukeop/tinycrawl-backend

I've worked on the backend for some time, and recently I started developing the frontend part as well. They're being developed simultaneously, bit by bit, to match functionality.

**Comment by jrswab** [comment]
I too would like to use this logo for my free and open-source project called Archivatory. It's a simple web-UI that allows people to easily upload their content to the Interplanetary File System (IPFS).

https://github.com/jrswab/archivatory

### The Problem:
IPFS is quickly becoming the backbone of decentralized content creation with many apps using this protocol to store their users content. Unfortunately, there is no easy way for the average content creator to use IPFS natively if they so choose.

It takes a live server running Linux 24/7 and running the IPFS software even to have the ability to upload. Then the creator has to learn the commands and how to navigate the CLI before they can ever get their content into the InterPlanetary File System.

### The Solution:
This project solves that very issue. Taking out all the hard backend work and leaving the user with a simple webpage to upload their content an get their IPFS hash with a link to view their content. Getting the creator's content on IPFS so it can potentially exist forever is now seamless. Freeing up the creator's time to create more epic content.

#### Try it out at [archivatory.com](https://archivatory.com)

**Comment by jhpratt** [comment]
[r/Spacex Mission Control](https://github.com/r-spacex/mission-control) is a web-based application to host launch threads on r/SpaceX. Currently, its usage is relatively limited, but I am currently working on a bottom-up rewrite that will provide a combined interface with live updates, push notifications, and integrated streaming (potentially chat as well). It will have everything people will want to know about a launch while it's happening, and I expect it to have thousands (or tens of thousands) of users during each launch.

**Comment by malikolivier** [comment]
I am interested to claim this logo for an ongoing free software project I and some friends are developing: [aflak](https://github.com/aflak-vis/aflak).

This is a astronomical dataset visualization/analysis platform, providing an node editor-like visual programming interface with real-time feedback.

The project is still fairly young and under developments (far from being completely usable as of now). The main target users are the professional astronomy community.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/cosmos-guide.jpg">

Congrats @jwu910   
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
