### ISSUE TITLE
watch-bob

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#30]
<img src="https://arasatasaygin.github.io/openlogos/logos/watch-bob.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/watch-bob-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by grsmv** [comment]
This one is amazing. I'm starting open source project immediately :)

**Comment by jbrooksuk** [comment]
Hi @arasatasaygin, this is a great idea and I'd love to represent your work in my project.

"watch-bob" looks like a great logo for [Cachet](/CachetHQ/Cachet). Cachet is an open source status page system with over 8k stars on GitHub and tens of thousands of installations from many companies in many industries, including Nestle, Bosch and Mozilla.

Cachet means "to have status" and "watch-bob" here oozes status (it's the bow-tie). Dogs are man's best friends and are highly respected animals around the world.

Thank you 😄

**Comment by arasatasaygin** [comment]
Cachet looks impressive @jbrooksuk 
Thanks for considering this logo for your project.

**Comment by jbrooksuk** [comment]
Thank you @arasatasaygin 😌

**Comment by maciossek** [comment]
Hello there!

we do have an open source project: It's about gathering dog turds, via react-native (Android and iOS) and web. We are currently still in beta, because we lack a logo! So we kinda need App Icons and Map markers for dog turds:  http://turds.dog/

Would it be possible for you to come up with nice matching turd marker for a Maps application?

Here are our repos: https://github.com/thr33think

**Comment by arasatasaygin** [comment]
Best turds application ever @maciossek :) Thanks for claiming. 
I'll try to help winning projects as much as I can, so yes if you get this logo you will get the turd marker. Cheers.

**Comment by betsythefc** [comment]
Hello! I have a project called JiraDog that needs a logo! JiraDog takes information from Jira's (a ticketing system) API, does some math like finding averages and pushes the results to DataDog, a metric tracking service. I'd love this logo for the project! https://github.com/betsythefc/jiradog

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/watch-bob-guide.jpg">

Congrats @jbrooksuk  🐶
Cachet already had a good foundation. I tried to mash current palette and watch-bob. Resource file will have the original version as well.

Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras

**Comment by jbrooksuk** [comment]
Thanks @arasatasaygin!

**Comment by HabibMAALEM** [comment]
Hi @arasatasaygin, you do a great job

I wanted to know if you still have a watchdog 🐶 logo  for an open source project
https://github.com/groupe-edf/watchdog

Thanks

**Comment by arasatasaygin** [comment]
Hey @HabibMAALEM 
This logo is given to @jbrooksuk earlier. If he wants to transfer it to you it is possible as James has the creative rights at this point, not me.

Cheers.

**Comment by HabibMAALEM** [comment]
Hi @jbrooksuk, i want to know if you're always using this logo, if it's not the case I would be grateful if you can transfer the ownership rights to me.
