### ISSUE TITLE
Great work! What tool did you use to create these?

### ISSUE THREAD

**Issue by hello-w0r1d** [arasatasaygin/openlogos#34]
These look extremely elegant. What's the flow like to generate such logos?

**Comment by arasatasaygin** [comment]
Hi @hello-w0r1d 
I use pen and paper to sketch and Adobe illustrator to vectorize logos. You can watch the legendary Aaron Draplin from https://www.youtube.com/watch?v=zOPA0NaeTBk
I am exactly following same process.
Hope it helps.
Cheers.
