### ISSUE TITLE
The project ISY

### ISSUE THREAD

**Issue by zbeboy** [arasatasaygin/openlogos#37]
Hello,
        Firstly, I'm very happy about your project openlogos. Because I hope have a logo for my project [ISY](https://github.com/zbeboy/ISY). This project was maked for our school，help teachers and students to learn and better life. Can you design a logo for ISY?  I'll be thank you very much. Of course, welcome to websit [ISY](https://www.zbeboy.top/). Thanks.

**Comment by arasatasaygin** [comment]
Hi @zbeboy 
ISY looks good.
You need to select a logo from readme file or http://openlogos.org/ and claim that specific logo, for your project.
Cheers.
