### ISSUE TITLE
Web Application For Open Logos

### ISSUE THREAD

**Issue by m-henderson** [arasatasaygin/openlogos#38]
do you think that there is a better way to vote and declare logos than using the GitHub website? If you think we could build a website for this, let me know. I will start the project, maintain the project, buy a domain, and pay for hosting. 

What do you all think?

**Comment by arasatasaygin** [comment]
Hi @m-henderson 
Thanks for the offer. Actually I'm planning to build it myself.

This is the plan:
- First of all, I'll focus on this very first batch of logos and distribution as it is the main premise of project. I'll give support on using these logos with proper type, guidelines and other promotional usage for projects.
- On the second batch, I'll try to include new designers, if there is enough support from design community. Which can validate a need for platform and create enough experience to productize it.
- And for the third batch I would love to build a minimal platform to host the community with a more suitable environment and better capabilities hopefully.

It's a high level roadmap but it is suitable for my pace. If you are planning to create a platform for helping open source projects yourself though, make it happen. Good luck.

Cheers.
