### ISSUE TITLE
quick-fingers

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#4]
<img src="https://arasatasaygin.github.io/openlogos/logos/quick-fingers.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/quick-fingers-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by claudiodangelis** [comment]
Hi @arasatasaygin, thanks for this project.

I'd like to adopt the quick-fingers logo for [qr-filetransfer](https://github.com/claudiodangelis/qr-filetransfer), a command line utility written in Go to transfer files over wifi from a device to another by scanning a QR code without leaving the terminal. 

Here's a demo gif of how it works: [qr-filetransfer demo](https://github.com/claudiodangelis/qr-filetransfer/blob/master/demo.gif).

The project had a very good response from the community, who contributed with pull requests, feature requests, bug reporting and code reviewing.

A hand holding a lightning bolt is a perfect representation of qr-filetransfer
- it's fast (no configuration, no 3rd party provider, no apps to install on the device)
- the transfer feels handheld

Thanks!
Claudio

**Comment by arasatasaygin** [comment]
Hello @claudiodangelis 
Anything that keeps me on my terminal and chair is awesome :) Thanks for claiming.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/quick-fingers-guide.jpg">

Congrats @claudiodangelis   
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting.
Cheers

~ Aras
