### ISSUE TITLE
Logo for Open Source Avouch Linux Operation System

### ISSUE THREAD

**Issue by qurbanullah** [arasatasaygin/openlogos#41]
I have developed my own operating system distribution based on Linux kernel from scratch.
I am not good in logo design.
I wanted a logo for my Operating System and website https://avouch.org.
I am unable to decide which logo should be best suited?

The feature of Operating Systems are:-
Secure
Reliable
User friendly

**Comment by arasatasaygin** [comment]
Hello @qurbanullah 
Your project looks great.
You need to select a logo from readme file or http://openlogos.org/ and claim that specific logo, for your project. If you think there is no suitable logo in this batch you can wait for upcoming logos.
Cheers.
