### ISSUE TITLE
LinuxChix Argentina

### ISSUE THREAD

**Issue by vkmc** [arasatasaygin/openlogos#43]
Hi!

We are an open source community that aims to connect underrepresented people in open source and encourage more people to join us. We have a logo already, but we would like to simplify it. Would you be able to help us? Thanks for doing this!

Cheers,

Victoria

**Comment by arasatasaygin** [comment]
Hi @vkmc 
Thanks for your initiative. For the time being I'm trying to focus on open source projects.
If your community has any open source projects, feel free to select a logo from readme file or http://openlogos.org/ and claim that specific logo, for your project.
Cheers.

**Comment by arasatasaygin** [comment]
BTW your illustration on homepage is kickass @vkmc

**Comment by vkmc** [comment]
Hi @arasatasaygin thanks for the quick reply. Sorry, I misunderstood the process. If we get to work on an open source project ourselves, I'll make sure to apply for one of your logos, they are awesome!

The Robotux illustration is very cool yes, we owe this to a great designer. Still, we need to simplify it. We will start looking for designers to make this happen.

Thanks again!
