### ISSUE TITLE
Voting rules clarification

### ISSUE THREAD

**Issue by ThemesGuide** [arasatasaygin/openlogos#44]
In the rules it says...

> "Community can upvote your comment..."

Does this specifically mean 👍? Or do other positive reactions such as ❤️,🎉, etc... count as upvotes too?

**Comment by garrettw** [comment]
I would imagine at least ❤️  would count in addition to 👍 . But so far it hasn't been an issue at all so I imagine it would be addressed if/when it comes down to that.

**Comment by jwu910** [comment]
If :heart: is also counting, technically everyone would have had the opportunity to vote twice.

**Comment by ThemesGuide** [comment]
@jwu910 - Exactly, that's my concern

**Comment by m-henderson** [comment]
there really needs to be a specific web application built for the voting of logos. github just isn't the place to do it.

**Comment by thiamsantos** [comment]
One option is to use [GH Pools](https://gh-polls.com/).

**Comment by styfle** [comment]
@thiamsantos Does that take into account the github user name? If not, then the user could vote multiple times by using different browsers or computers.

**Comment by thiamsantos** [comment]
@styfle a single vote per IP is allowed.

**Comment by styfle** [comment]
@thiamsantos That means one person could vote multiple times using their mobile phone.

I think a simpler answer is to only count 👍 emoji when tallying votes.

**Comment by jwu910** [comment]
Why not just use github? I think this is fine. OP wants to target open source developers, and why not use a platform that open source developers are on?

**Comment by arasatasaygin** [comment]
Didn't have any edge cases and gave away all logos according to 👍
Thanks for the support.

Cheers
~ Aras
