### ISSUE TITLE
Zigbee2mqtt logo request (1.3k+ stars)

### ISSUE THREAD

**Issue by Koenkk** [arasatasaygin/openlogos#46]
**First of all I don't know if it is possible to request a logo, if not, feel free to close this.**

I would like to request a logo for [zigbee2mqtt](https://github.com/koenkk/zigbee2mqtt). Zigbee2mqtt is an opensource Zigbee bridge which integrates well with existing home automation software. Currently there is no logo but I would like to have one as the project is getting bigger and bigger.

Please let me know if you are interested!

**Comment by arasatasaygin** [comment]
Hey @Koenkk 
Thanks for your interest. zigbee2mqtt looks great. For the time being, I don't design logos on demand. But I will let you know on the second batch of open logos.
Cheers.
