### ISSUE TITLE
cloud API, AI

### ISSUE THREAD

**Issue by ghost** [arasatasaygin/openlogos#50]

**Comment by arasatasaygin** [comment]
Hey Lucas,
Your idea sounds good, but this project does not involve monetary focus or AI generated content.
Good luck with your project though 👍

**Comment by lucasnuic** [comment]
> Hey Lucas,
> Your idea sounds good, but this project does not involve monetary focus or AI generated content.
> Good luck with your project though 👍

Hi arasatasaygin. Thank you for your kind words. 🙂
