### ISSUE TITLE
kareem

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#6]
<img src="https://arasatasaygin.github.io/openlogos/logos/kareem.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/kareem-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by neilgupta** [comment]
This is a good logo for https://github.com/neilgupta/Sherlock

Sherlock is a natural language parser for entering events in javascript.

Thanks for the great project, @arasatasaygin!

**Comment by arasatasaygin** [comment]
Hello @neilgupta 
I tried a couple of text with Sherlock and it is pretty accurate 👍 Thanks for claiming.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/kareem-guide.jpg">

Congrats @neilgupta      
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting.
Cheers

~ Aras
