### ISSUE TITLE
foxy

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#7]
<img src="https://arasatasaygin.github.io/openlogos/logos/foxy.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/foxy-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by thiamsantos** [comment]
Hi @arasatasaygin, congratulations on the excellent initiative! :tada: 

I'm building a key-value in memory database with elixir, with the goals of be fault tolerant and fast. I would like to use this logo to represent the project and be the official mascot of the project. https://github.com/thiamsantos/spike/

**Comment by arasatasaygin** [comment]
Cool project @thiamsantos

**Comment by Cryptophobia** [comment]
Hi @arasatasaygin ,

Awesome initiative! I am one of the maintainers for the open source fork of Deis Workflow, called Team Hephy. Our project is a PaaS built on top of Kubernetes. We are current merging new features, working on documentation website, and the first release of the fork. This logo fits well with our color scheme on the current website, and we would like to try to get this one.

Our project solves the problem of providing a easier solution for teams and companies to create their own PaaS deployment workflows on top of Kubernetes. It also helps teams moving toward Kubernetes.

https://teamhephy.com/
https://github.com/teamhephy/

**Comment by arasatasaygin** [comment]
Hey @Cryptophobia 
Thanks for claiming. Good luck.

**Comment by rivetchip** [comment]
Hey @arasatasaygin , Wow, I find those rather cute, ahah! Nice idea  :smile: . I hope more designer will join.

I'm currently building a simple Movie collection app for Linux/Windows & Android ( using Electron and Android Webview ). As the title say, you'll be able to manage your favorites movies. Search and import from TMDb is also possible.

I wanted a nice GCStar alternative for Linux for myself and I ended up doing this project.

Progress are slow but still active (doing it on my free time).

:bug: If you are interested : https://github.com/rivetchip/electron-simple-movie-collection

**Comment by oxr463** [comment]
@thiamsantos looks like you never claimed this. Would you be willing to release it for use with another project?

**Comment by Cryptophobia** [comment]
We'd still be interested to take this foxy :fox_face: at www.teamhephy.com if available. :)

**Comment by thiamsantos** [comment]
@Cryptophobia I endedup renaming the repo to https://github.com/thiamsantos/spike-kv. But that project is mostly dead now, I didn't have time to work on it. I would be happy to sending the assets to you to use on hephy and removing the logo from my project. Actually I think never used the coupon for free stickers, I could also send to you. WDYT?  @arasatasaygin do you see any problem with that?

**Comment by arasatasaygin** [comment]
Hi @thiamsantos,
As you are the winner, I trust and support your decision to pass the logo to @Cryptophobia .
Seeing the 🦊 on a live project would make me happy as well.

Enjoy and be safe.
~Aras

**Comment by thiamsantos** [comment]
@Cryptophobia Feel free to reach me out at `thia.mdossantos@gmail.com`, I will send to you the assets of the logo :)

**Comment by Cryptophobia** [comment]
@thiamsantos , thank you for passing the logo and sorry to hear about your project. Hope you are working on better and greater things to come! 

I have just emailed you and I will add the foxy (to replace our ship logo) to our main repo, website, and slack channels sometime this week. We are very excited and will post back here. :)

**Comment by Cryptophobia** [comment]
Thank you! Received the logo today via email from @thiamsantos . @arasatasaygin do you happen to have a Keybase account (want to send you something for the logo)?

**Comment by Cryptophobia** [comment]
![hephy+logo+type](https://user-images.githubusercontent.com/15237494/81621427-5c4e6e00-93bc-11ea-80cf-b49a647b3826.png)

:bowing_man: :fox_face:

**Comment by arasatasaygin** [comment]
❤️🦊

**Comment by Cryptophobia** [comment]
![Selection_149](https://user-images.githubusercontent.com/15237494/82377766-2def1500-99f2-11ea-8a67-30a635aa8108.png)
