### ISSUE TITLE
speedy

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#8]
<img src="https://arasatasaygin.github.io/openlogos/logos/speedy.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/speedy-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by tombh** [comment]
This seems a perfect fit with https://github.com/tombh/texttop - a text-based browser for people on slow connections. It even uses 8-bit style pixels in the terminal - so the logo is most appropriate. I'm going to be releasing a complete rewrite (and rename to _Browsh_) in the next few weeks. The repo has 3.4k stars.

**Comment by arasatasaygin** [comment]
@tombh where have you been while I was traveling SE Asia. Good job on texttop. I'll definitely use it on my upcoming travels. Also speedy is a great match with texttop.

**Comment by tombh** [comment]
I'm in China at the moment, in a city called Kunming, not that far from Thailand and Vietnam. But I've also spent a lot of time on Java in Indonesia.

Thanks for the support and thanks for your project :) I'm looking forward to befriending Speedy :D

**Comment by tombh** [comment]
Oh BTW, so do you think this logo will be given out on the 8th of July, because it's the #8 issue?

**Comment by tombh** [comment]
I see, thanks. I was just wondering about maybe planning to release Browsh the same day I might be lucky enough to get this logo. But it might be a rush anyway.

**Comment by rivetchip** [comment]
Speedy the snail, thats brilliant :smile:

@tombh I think thats a perfect match too !

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/speedy-guide.jpg">

Congrats @tombh  🥇 

Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts and sticker mule voucher.

Cheers

~ Aras

**Comment by garrettw** [comment]
Love that heading font!

**Comment by tombh** [comment]
Thank you so much! I'm so happy :)

**Comment by arasatasaygin** [comment]
🔥🔥

**Comment by garrettw** [comment]
@tombh just wanted to let you know -- I was pleasantly surprised to run across Browsh organically in yesterday's issue of Codrops. I saw the logo and thought to myself, "Wow, someone stole the Texttop logo!" -- not knowing the project had been renamed. :smile:

**Comment by tombh** [comment]
Thanks @garrettw I'm very pleased you made the connection, the logo is clearly doing its job of sticking in people's memories :D

**Comment by garrettw** [comment]
Honestly I would probably recognize most of the logos here just because I've been watching the repo closely.

**Comment by tombh** [comment]
https://www.brow.sh/assets/images/logo.svg

**Comment by alrra** [comment]
@tombh Thanks!
